import { FilterPrimaryCategory } from '../types/filter';
import { GalleryImageData } from '../types/gallery';
import { ASSETS_PATH } from '../utils/constants';

export const galleryCategories: FilterPrimaryCategory[] = [
  {
    id: 'aikido',
    name: 'Aikido',
    subCategories: [
      { id: 'rfc-adults', name: 'Adults' },
      { id: 'wpi', name: 'WPI' },
    ],
  },
  {
    id: 'capoeira',
    name: 'Capoeira',
    subCategories: [
      { id: 'rfc-adults', name: 'Adults' },
      { id: 'wpi', name: 'WPI' },
    ],
  },
  {
    id: 'outdoor',
    name: 'Outdoor Programs',
  },
  {
    id: 'react',
    name: 'REaCT',
    subCategories: [
      { id: 'rfc-adults', name: 'Adults' },
      { id: 'wpi', name: 'WPI' },
      { id: 'competitions', name: 'Competitions' },
    ],
  },
  {
    id: 'events',
    name: 'Special Events',
    subCategories: [
      { id: 'nebisensei022019', name: 'Nebi Sensei Aikido Seminar Feb 2019' },
    ],
  },
];

const galleryImages: GalleryImageData[] = [
  // rfc
  // react
  {
    caption: 'REaCT circle to close out class.',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/react-class-circle.png`,
    subCategoryId: 'wpi',
    tags: ['class'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/react-class-circle.png`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/class-group-1.jpg`,
    subCategoryId: 'wpi',
    tags: ['class', 'group'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/class-group-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/karen-1.jpg`,
    subCategoryId: 'wpi',
    tags: ['portraits'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/karen-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-1.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga', 'group'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-action-1.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga', 'action'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-action-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-action-2.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga', 'action'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-action-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-action-3.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga', 'action'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-action-3.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-face-1.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga', 'portraits'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-face-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-face-2.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga', 'portraits'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-face-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-group-1.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga', 'group'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-group-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-stretch-1.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-stretch-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-stretch-2.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-stretch-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-stretch-3.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-stretch-3.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'react',
    src: `${ASSETS_PATH}/programs/REaCT/naga-stretch-4.jpg`,
    subCategoryId: 'competitions',
    tags: ['naga'],
    thumbnail: `${ASSETS_PATH}/programs/REaCT/naga-stretch-4.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  // capoeira
  // aikido
  // special-events
  // // Nebi Sensei 02-2019
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-1.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['action'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-2.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['class'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-3.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['class'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-3.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-4.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['group'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-02-08-4.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-group-1.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['group'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-group-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-group-2.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['group'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-group-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-john-1.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['action'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-john-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-john-2.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['action'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-john-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-1.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['action'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-2.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['action'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-3.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['action'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-3.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'events',
    src: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-group-1.jpg`,
    subCategoryId: 'nebisensei022019',
    tags: ['group'],
    thumbnail: `${ASSETS_PATH}/events/nebisensei022019/nebi-wpi-group-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  // outdoor
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/martin-hike-1.jpg`,
    tags: ['hiking'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/martin-hike-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/martin-hike-2.jpg`,
    tags: ['hiking'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/martin-hike-2.jpg`,
    thumbnailHeight: 300,
    thumbnailWidth: 200,
  },
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/paint-run.jpg`,
    tags: ['runs'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/paint-run.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/white-mtns-1.jpg`,
    tags: ['hiking'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/white-mtns-1.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/white-mtns-2.jpg`,
    tags: ['hiking'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/white-mtns-2.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/white-mtns-4.jpg`,
    tags: ['hiking'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/white-mtns-4.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/white-mtns-3.jpg`,
    tags: ['hiking'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/white-mtns-3.jpg`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
  {
    caption: '',
    categoryId: 'outdoor',
    src: `${ASSETS_PATH}/programs/Outdoor/white-mtns-group.png`,
    tags: ['hiking'],
    thumbnail: `${ASSETS_PATH}/programs/Outdoor/white-mtns-group.png`,
    thumbnailHeight: 200,
    thumbnailWidth: 300,
  },
];

export default galleryImages;
